execute "an Plugin.Arduino.Verify                 :ArduinoVerify<CR>"
execute "an Plugin.Arduino.Upload                 :ArduinoUpload<CR>"
execute "an Plugin.Arduino.Upload\\ and\\ Monitor :ArduinoUploadAndSerial<CR>"
execute "an Plugin.Arduino.Choose.Board           :ArduinoChooseBoard<CR>"
execute "an Plugin.Arduino.Choose.Board           :ArduinoChooseProgrammer<CR>"
